#!/bin/sh
set -e

case "$1" in
    purge|remove)
        # Update desktop database
        if [ -x "$(command -v update-desktop-database)" ]; then
            update-desktop-database -q
        fi
        
        # Update icon cache
        if [ -x "$(command -v gtk-update-icon-cache)" ]; then
            gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
        fi
        ;;
        
    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
        
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
