#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        # Clean up any temporary files that might have been left behind
        rm -rf /tmp/WowUSB.*
        ;;
        
    failed-upgrade)
        ;;
        
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
